.PHONY: clean All

All:
	@echo "----------Building project:[ Morpion - Debug ]----------"
	@cd "Morpion" && "$(MAKE)" -f  "Morpion.mk"
clean:
	@echo "----------Cleaning project:[ Morpion - Debug ]----------"
	@cd "Morpion" && "$(MAKE)" -f  "Morpion.mk" clean
