#ifndef __EvtFramePrincipal__
#define __EvtFramePrincipal__

/**
@file
Subclass of FramePrincipal, which is generated by wxFormBuilder.
*/

#include "FramePrincipal.h"

//// end generated include
#include <string>
#include <wx/log.h>
#include <wx/string.h>
#include <wx/sound.h>
//#include <wx/mediactrl.h>
#define FILENAME "music.wav"
/** Implementing FramePrincipal */
class EvtFramePrincipal : public FramePrincipal
{
	protected:
		// Handlers for FramePrincipal events.
		void OnClickBC0( wxCommandEvent& event );
		void OnClickBC1( wxCommandEvent& event );
		void OnClickBC2( wxCommandEvent& event );
		void OnClickBC3( wxCommandEvent& event );
		void OnClickBC4( wxCommandEvent& event );
		void OnClickBC5( wxCommandEvent& event );
		void OnClickBC6( wxCommandEvent& event );
		void OnClickBC7( wxCommandEvent& event );
		void OnClickBC8( wxCommandEvent& event );
	public:
		/** Constructor */
		EvtFramePrincipal( wxWindow* parent );
	//// end generated class members
    private:
        
        bool AlgoX();
        bool AlgoO();
        void Restart();
        bool AgloAllUsed();
        bool MUSIC();
        void Print(wxString message);
        wxString table[3][3];
        wxString skin="";
        wxSound *sound;
        //wxMediaCtrl *music;




};

#endif // __EvtFramePrincipal__
