.PHONY: clean All

All:
	@echo "----------Building project:[ Tree - Debug ]----------"
	@cd "Tree" && "$(MAKE)" -f  "Tree.mk"
clean:
	@echo "----------Cleaning project:[ Tree - Debug ]----------"
	@cd "Tree" && "$(MAKE)" -f  "Tree.mk" clean
